### ISSUE TITLE
Allow missing name and version by default

### ISSUE THREAD

**Issue by callumlocke** [HenrikJoreteg/fixpack#21]
I know this rule is configurable, but fixpack is too small a thing to have to remember configuration details for.

I just can't see any value in fixpack dying when there's no name field. There's nothing wrong with a package.json without a name. It just means you can't publish it. And npm already enforces that point, so what's the value in fixpack doing the same?

**Comment by slang800** [comment]
What is the use-case for a name-less, version-less package?

I'd be fine with making it not fail by causing it to default to a version `1.0.0` and the name of the directory that it's in (or something like that)... But I can't imagine why you wouldn't have a name/version for a package, even if it's not going to be published. You can't even `npm link` it without a name.

**Comment by callumlocke** [comment]
> What is the use-case for a name-less, version-less package?

Applications. E.g. an app you are going to deploy to a server (as opposed to publish or link or install as a dep). There is literally no benefit in setting the name and version fields in most apps, so I don't set them, I don't want pointless things in my codebase that I might forget to keep up to date.

**Comment by slang800** [comment]
> There is literally no benefit in setting the name and version fields in most apps

Yeah there is - how do you even talk with the rest of your team about a project that doesn't have a name? Or remember which directory you put the code in? Or which repo to clone it from? 

For the version, do you just deploy with commit SHAs? How would you remember where you introduced a breaking change, or even check which version you're running on a given system?

I suppose you could get around that stuff it if you're dumping all your code in a Docker container or something, manually getting deps, and never doing an `npm install` or `link`... But even then I don't think it's a good idea because the [docs](https://docs.npmjs.com/files/package.json) say:

> The most important things in your package.json are the name and version fields. Those are actually required, and your package won't install without them.

... So I would expect other tools to break when the name/version isn't there and I certainly wouldn't want to promote the omission of those fields, especially when it's done accidentally.

**Comment by HenrikJoreteg** [comment]
closing due to age and the fact that I personally want them to have a name /me shrugs.
